---
title: "Optimizing Concurrent Queues for Throughput"
author: "Oliver Michel"
date: "10/27/2018"
output:
  html_document: default
---

```{r setup, include=FALSE, message=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  dev = c('png', 'pdf'), 
  fig.align = 'center',
  fig.height = 2.5,
  fig.width = 5.5,
  fig.keep = 'high',
  fig.path = 'fig/') 

inside_knitr = function() {
    length(knitr::opts_current$get()) > 0
}

library(readr)
library(ggplot2)
library(reshape2)
library(plyr)

source('../config-r/config.R')
```


|Name      |Memory Layout|Thread Safety  |Zero-Copy Enqueue|
|----------|-------------|---------------|-----------------|
|queue1    |Linked List  |Locks          |no               |
|queue2    |Array        |Locks          |no               |
|queue3    |Linked List  |Memory Barriers|no               |
|queue4    |Array        |Memory Barriers|available        |
|queue5    |Array        |Memory Barriers|available        |
|moodycamel|Array        |Memory Barriers|available        |

```{r import, message=FALSE}
data <- read_csv('results/102818-8b-gcc8-i75557u.csv', col_names = c('queue', 'count', 'time', 'throughput'))
```

```{r summary}
tp_summary <- arrange(
  ddply(data, 'queue', summarize, 
      count=length(throughput), mean=mean(throughput), sd=sd(throughput),
      q25=quantile(throughput, .25), q50=quantile(throughput, .50), q75=quantile(throughput, .75),
      min=min(throughput), max=max(throughput)
), mean)

if (inside_knitr()) knitr::kable(tp_summary) else tp_summary
```

```{r means, message=FALSE}
ggplot(tp_summary, aes(x=reorder(queue, mean), y=mean)) +
    geom_bar(stat='identity', fill='#003366', width=0.65) +
    theme_om() + ylab('Mean Throughput [M records/s]') + xlab('Queue')
```

```{r cdf,  message=FALSE}
ggplot(data, aes(throughput, color=queue)) + stat_ecdf(size=0.75) +
  theme_om() +
  theme(legend.position = c(0.99, 0.5), legend.title = element_blank()) +
  xlab('Throughput [M records/s]') + ylab('CDF') + scale_color_brewer(palette="Dark2")
```